version: '3.8'
services:

  db:
    image: postgres:14.1-alpine
    restart: always
    environment:
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    ports:
      - '5432:5432'
    volumes:
      - db:/var/lib/postgresql/data
    container_name: "db"

  application:
    depends_on:
      - db
    command: bash -c "sleep 5 && alembic upgrade head && uvicorn backend.app:app --host 0.0.0.0 --port 4567"
    build:
      context: ../ # backend
      dockerfile: ./docker/application/Dockerfile
    image: application
    ports:
      - "4567:4567"
    container_name: "application"

volumes:
  db:
    driver: local